---
# tasks file for mysql
- name: Install the MySQL packages
  yum:
    name: ['mariadb-server','mariadb','MySQL-python']
    state: present

- name: Starting Mariadb
  service:
     name: mariadb
     state: started

- name: Enabling Mariadb
  service:
   name: mariadb
   enabled: yes


- name: Update MySQL root password for all root accounts
  mysql_user: login_user=root login_password={{ mysql_root_pass }} name=root host={{ item }} password={{ mysql_root_pass }} state=present check_implicit_admin=yes 
  with_items:
        - "{{ ansible_hostname }}"
        - localhost

- name: Copy the root credentials as .my.cnf file
  template: src=root.cnf.j2 dest=~/.my.cnf mode=0600 


- name: Ensure Anonymous user(s) are not in the database
  mysql_user: name='' host={{ item }} state=absent 
  with_items:
        - localhost
        - "{{ ansible_hostname }}"

- name: Remove the test database
  mysql_db: name=test state=absent 

- name: Creating database
  mysql_db:
    name: "{{ db_name }}"
    state: present
  notify:
       - Restart MySQL

